[build-system]
requires = [
    "setuptools>=42",
    "wheel",
	"numpy >= 1.22.1",
    "scipy >= 1.7.3",
    "tifffile == 2021.11.2",
    "pyside2 == 5.15.1",
    "shiboken2 == 5.15.1",
    "pyglet == 1.4.10",
    "stitch2d >= 1.0",
    "tk == 0.1.0",
    "opencv-contrib-python == 4.5.5.62",
    "ome-types == 0.2.4",
    "datetime == 4.3",
    "openpyxl == 3.0.9",
    "pillow == 9.0.0",
	"scikit-image >= 0.19.1"
]

build-backend = "setuptools.build_meta"

