[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "glover"
authors = [
    {name = "Francesco Sheiban", email = "frances.j.shei@gmail.com"},
    {name = "Robin De Schepper", email = "robingilbert.deschepper@unipv.it"},
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: BSD License",
]
requires-python = ">=3.8"
dynamic = ["version", "description"]
dependencies = [
    "vispy~=0.9",
    "pyglet~=1.5",
    "bsb~=4.0.0a0",
    "trimesh~=3.10",
    "numpy~=1.22",
]
