"""
    REST ML-AI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import os.path
from setuptools import setup, find_packages  # noqa: H301

# The directory containing this file
HERE = os.path.abspath(os.path.dirname(__file__))

NAME = "ml_tracking-api"
VERSION = "1.2.8"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

# The text of the README file
with open(os.path.join(HERE, "README.md")) as fid:
    README = fid.read()

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="REST ML-AI API",
    long_description=README,
    long_description_content_type="text/markdown",
    author="Eimantas Noreika",
    author_email="noreika.eimantas@gmail.com",
    url="https://github.com/EimantasN/Equusight_BackEnd",
    keywords=["OpenAPI", "OpenAPI-Generator", "REST ML-AI API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True
)
