[tool.poetry]
name = "factory-ai"
version = "0.1.0"
description = ""
authors = ["Jidhu Mohan <jidhu.mohan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
tensorflow = "2.6"
tensorflow-transform = "1.4"
apache-beam = "^2.35.0"
future = "^0.18.2"
keras = "2.6"
tensorflow-data-validation = "1.4"
scikit-learn = "^1.0.2"
keras-tuner = "^1.1.0"
matplotlib = "^3.5.1"
gekko = "^1.0.2"
opencv-python = "4.4.0.46"
gym = "^0.21.0"
mediapipe = "^0.8.9"
pyglet = "^1.5.21"
bayesian-optimization = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
