from setuptools import setup
setup(name="cryx4ck",
version="1.1",
description="This package is a multi text cryptograpy package.",
long_description=open('README.md').read(),
author="Rakib Hossain",
author_email="teamx4ck@gmail.com",
license=open('License').read(),
classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'License :: OSI Approved :: Apache Software License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: Implementation :: CPython',
        'Programming Language :: Python :: Implementation :: PyPy'
 ],
packages=['cryx4ck'],
install_requires=[])
