
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-20T02:15:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "40848b9afe7278bb273d6028a5b384e5f492afec",
 "version": "0.4.dev2208"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
