name: Build wheels and publish to PyPI

on:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build wheel
        run: |
          python -m pip install build
          python -m build --wheel --sdist --outdir dist
      - name: Store wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist/*

  upload_wheels:
    name: Upload wheels to PyPI
    runs-on: ubuntu-latest
    needs: [build_wheels]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/
