[tool.poetry]
name = "rootbridge"
version = "0.0.2"
description = "Bridge to the silos."
authors = ["Angelo Gladding <angelo@ragt.ag>"]
license = "CC0-1.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
