
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-18T15:58:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a07c20925b04dfa8920c18ca83ff28648f7b5579",
 "version": "v2.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
