[tool.poetry]
name = "dictencli"
version = "0.1.2"
description = "A simple commandline dictionary app."
authors = ["Nikhil <nikhilomkar99@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
dictencli = "dictencli.dictencli:dict_app"

[tool.poetry.dependencies]
python = "^3.8"
certifi="^2021.10.8"
charset-normalizer="^2.0.12"
click="^8.0.3"
colorama="^0.4.4"
commonmark="^0.9.1"
idna="^3.3"
playsound="^1.2.2"
Pygments="^2.11.2"
requests="^2.27.1"
rich="^11.2.0"
typer="^0.4.0"
urllib3="^1.26.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
