
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-23T21:15:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "99f28d02c0c9a7b858e682ab42248f935d0ca72e",
 "version": "0.0.65.post0.dev141"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
