[tool.black]
line-length = 100
target-version = ["py36", "py37"]
skip-numeric-underscore-normalization = true
exclude = '/(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|_build|build|dist|migrations)/'

[tool.towncrier]
package = "pulp_cookbook"
filename = "CHANGES.rst"
directory = "CHANGES/"
title_format = "{version} ({project_date})"
template = "CHANGES/.TEMPLATE.rst"
issue_format = "`#{issue} <https://github.com/pulp/pulp_cookbook/issues/{issue}>`_"

[tool.check-manifest]
ignore = [
    ".bumpversion.cfg",
    ".gitleaks.toml",
    "CHANGES/**",
    "CONTRIBUTING.rst",
    "CODEOWNERS",
    "HISTORY.rst",
    "dev_requirements.txt",
    "doc_requirements.txt",
    "docs/**",
    ".flake8",
    "flake8.cfg",
    "template_config.yml",
    ".travis/**",
    ".travis.yml",
    ".pep8speaks.yml",
    ".ci/**",
    ".github/**"
]
