[tool.poetry]
name = "pyechelle"
version = "0.2.3"
description = "A fast generic spectrum simulator"
authors = ["Julian Stuermer <julian@stuermer.science>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/Stuermer/pyechelle"
repository = "https://gitlab.com/Stuermer/pyechelle"
documentation = "https://stuermer.gitlab.io/pyechelle/"
include = ["models/available_models.txt"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
matplotlib = "^3.3.2"
astropy = "^5.0"
h5py = "^3.1.0"
scipy = "^1.5.2"
parmap = "^1.5.2"
numpy = "<=1.21"
numba = "^0.55.0"
plotly = "^5.4.0"
pandas = "^1.3.4"
skycalc-ipy = "^0.1.3"
astroquery = "^0.4.4"
joblib = "^1.1.0"

[tool.poetry.dev-dependencies]
Sphinx = "^3.2.1"
hypothesis = "^6.36.1"
pytest = "^6.2.5"
coverage = { extras = ["toml"], version = "^6.3.1" }
sphinx-argparse = "^0.3.1"
sphinx-rtd-theme = "^1.0.0"
pytest-benchmark = "^3.4.1"
pytest-cov = "^3.0.0"
sphinx-autodoc-annotation = "^1.0-1"

[tool.coverage.paths]
source = ["pyechelle"]

[tool.coverage.run]
branch = true
source = ["pyechelle"]

[tool.coverage.report]
show_missing = true

[tool.poetry.scripts]
pyechelle = "pyechelle.simulator:main"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
