[tool.poetry]
name = "prima"
version = "0.1.0"
description = ""
authors = ["kivo360 <kivo360@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
matplotlib = "^3.5.1"
networkx = "^2.6.3"
parameterized = "^0.8.1"
plotly = "^5.6.0"
pytest = "^7.0.1"
scipy = "^1.8.0"
scikit-learn = "^1.0.2"
seaborn = "^0.11.2"
tabulate = "^0.8.9"
xarray = "^0.21.1"
wheel = "^0.37.1"
pandas = "^1.4.1"
fn = "^0.4.3"
funcy = "^1.17"
dill = "^0.3.4"
pathos = "^0.2.8"
numpy = "^1.22.2"
pytz = "^2021.3"
six = "^1.16.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
