# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intentionet/bfe/proto/snapshot/answer_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='intentionet/bfe/proto/snapshot/answer_status.proto',
  package='com.intentionet.bfe.snapshot',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2intentionet/bfe/proto/snapshot/answer_status.proto\x12\x1c\x63om.intentionet.bfe.snapshot*w\n\x0c\x41nswerStatus\x12\x19\n\x15\x41NSWER_STATUS_UNKNOWN\x10\x00\x12\x17\n\x13\x41NSWER_STATUS_READY\x10\x01\x12\x19\n\x15\x41NSWER_STATUS_PENDING\x10\x02\x12\x18\n\x14\x41NSWER_STATUS_FAILED\x10\x03\x62\x06proto3'
)

_ANSWERSTATUS = _descriptor.EnumDescriptor(
  name='AnswerStatus',
  full_name='com.intentionet.bfe.snapshot.AnswerStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ANSWER_STATUS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANSWER_STATUS_READY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANSWER_STATUS_PENDING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANSWER_STATUS_FAILED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=84,
  serialized_end=203,
)
_sym_db.RegisterEnumDescriptor(_ANSWERSTATUS)

AnswerStatus = enum_type_wrapper.EnumTypeWrapper(_ANSWERSTATUS)
ANSWER_STATUS_UNKNOWN = 0
ANSWER_STATUS_READY = 1
ANSWER_STATUS_PENDING = 2
ANSWER_STATUS_FAILED = 3


DESCRIPTOR.enum_types_by_name['AnswerStatus'] = _ANSWERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
