# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intentionet/bfe/proto/snapshot/interfaces.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='intentionet/bfe/proto/snapshot/interfaces.proto',
  package='com.intentionet.bfe.snapshot',
  syntax='proto3',
  serialized_options=b'Z-intentionet.com/bfe/proto/snapshot/interfaces',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/intentionet/bfe/proto/snapshot/interfaces.proto\x12\x1c\x63om.intentionet.bfe.snapshot\"\xd2\x02\n\nInterfaces\x12H\n\x07\x65ntries\x18\x01 \x03(\x0b\x32..com.intentionet.bfe.snapshot.Interfaces.EntryR\x07\x65ntries\x12\x1c\n\thostnames\x18\x02 \x03(\tR\thostnames\x12\'\n\x0finterface_names\x18\x03 \x03(\tR\x0einterfaceNames\x12\"\n\x0c\x64\x65scriptions\x18\x04 \x03(\tR\x0c\x64\x65scriptions\x1a\x8e\x01\n\x05\x45ntry\x12\x1a\n\x08hostname\x18\x01 \x01(\rR\x08hostname\x12%\n\x0einterface_name\x18\x02 \x01(\rR\rinterfaceName\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\rR\x0b\x64\x65scription\x12 \n\x0b\x62lacklisted\x18\x04 \x01(\x08R\x0b\x62lacklisted\"n\n$GetSnapshotPhysicalInterfacesRequest\x12!\n\x0cnetwork_name\x18\x01 \x01(\tR\x0bnetworkName\x12#\n\rsnapshot_name\x18\x02 \x01(\tR\x0csnapshotName\"q\n%GetSnapshotPhysicalInterfacesResponse\x12H\n\ninterfaces\x18\x01 \x01(\x0b\x32(.com.intentionet.bfe.snapshot.InterfacesR\ninterfacesB/Z-intentionet.com/bfe/proto/snapshot/interfacesb\x06proto3'
)




_INTERFACES_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='com.intentionet.bfe.snapshot.Interfaces.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='com.intentionet.bfe.snapshot.Interfaces.Entry.hostname', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='hostname', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interface_name', full_name='com.intentionet.bfe.snapshot.Interfaces.Entry.interface_name', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='interfaceName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='com.intentionet.bfe.snapshot.Interfaces.Entry.description', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='description', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blacklisted', full_name='com.intentionet.bfe.snapshot.Interfaces.Entry.blacklisted', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='blacklisted', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=420,
)

_INTERFACES = _descriptor.Descriptor(
  name='Interfaces',
  full_name='com.intentionet.bfe.snapshot.Interfaces',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='com.intentionet.bfe.snapshot.Interfaces.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='entries', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hostnames', full_name='com.intentionet.bfe.snapshot.Interfaces.hostnames', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='hostnames', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interface_names', full_name='com.intentionet.bfe.snapshot.Interfaces.interface_names', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='interfaceNames', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='descriptions', full_name='com.intentionet.bfe.snapshot.Interfaces.descriptions', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='descriptions', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_INTERFACES_ENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=420,
)


_GETSNAPSHOTPHYSICALINTERFACESREQUEST = _descriptor.Descriptor(
  name='GetSnapshotPhysicalInterfacesRequest',
  full_name='com.intentionet.bfe.snapshot.GetSnapshotPhysicalInterfacesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='network_name', full_name='com.intentionet.bfe.snapshot.GetSnapshotPhysicalInterfacesRequest.network_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='networkName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='snapshot_name', full_name='com.intentionet.bfe.snapshot.GetSnapshotPhysicalInterfacesRequest.snapshot_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='snapshotName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=532,
)


_GETSNAPSHOTPHYSICALINTERFACESRESPONSE = _descriptor.Descriptor(
  name='GetSnapshotPhysicalInterfacesResponse',
  full_name='com.intentionet.bfe.snapshot.GetSnapshotPhysicalInterfacesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='interfaces', full_name='com.intentionet.bfe.snapshot.GetSnapshotPhysicalInterfacesResponse.interfaces', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='interfaces', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=647,
)

_INTERFACES_ENTRY.containing_type = _INTERFACES
_INTERFACES.fields_by_name['entries'].message_type = _INTERFACES_ENTRY
_GETSNAPSHOTPHYSICALINTERFACESRESPONSE.fields_by_name['interfaces'].message_type = _INTERFACES
DESCRIPTOR.message_types_by_name['Interfaces'] = _INTERFACES
DESCRIPTOR.message_types_by_name['GetSnapshotPhysicalInterfacesRequest'] = _GETSNAPSHOTPHYSICALINTERFACESREQUEST
DESCRIPTOR.message_types_by_name['GetSnapshotPhysicalInterfacesResponse'] = _GETSNAPSHOTPHYSICALINTERFACESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Interfaces = _reflection.GeneratedProtocolMessageType('Interfaces', (_message.Message,), {

  'Entry' : _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), {
    'DESCRIPTOR' : _INTERFACES_ENTRY,
    '__module__' : 'intentionet.bfe.proto.snapshot.interfaces_pb2'
    # @@protoc_insertion_point(class_scope:com.intentionet.bfe.snapshot.Interfaces.Entry)
    })
  ,
  'DESCRIPTOR' : _INTERFACES,
  '__module__' : 'intentionet.bfe.proto.snapshot.interfaces_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.bfe.snapshot.Interfaces)
  })
_sym_db.RegisterMessage(Interfaces)
_sym_db.RegisterMessage(Interfaces.Entry)

GetSnapshotPhysicalInterfacesRequest = _reflection.GeneratedProtocolMessageType('GetSnapshotPhysicalInterfacesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSNAPSHOTPHYSICALINTERFACESREQUEST,
  '__module__' : 'intentionet.bfe.proto.snapshot.interfaces_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.bfe.snapshot.GetSnapshotPhysicalInterfacesRequest)
  })
_sym_db.RegisterMessage(GetSnapshotPhysicalInterfacesRequest)

GetSnapshotPhysicalInterfacesResponse = _reflection.GeneratedProtocolMessageType('GetSnapshotPhysicalInterfacesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSNAPSHOTPHYSICALINTERFACESRESPONSE,
  '__module__' : 'intentionet.bfe.proto.snapshot.interfaces_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.bfe.snapshot.GetSnapshotPhysicalInterfacesResponse)
  })
_sym_db.RegisterMessage(GetSnapshotPhysicalInterfacesResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
