[tool.poetry]
name = "saiph"
# Also modify in saiph/__init__.py
version = "0.2.6"
description = "A projection package"
authors = ["Zineb Bennis", "Julien Petot <julien@octopize-md.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
pandas = "^1.3"
matplotlib = "^3.4"
numpy = "^1.21"
scipy = "^1.7"
scikit-learn = "^1.0"

[tool.poetry.dev-dependencies]
Sphinx = "^4.2"
ipykernel = "^6.4"
sphinx-rtd-theme = "^1.0"
jupyter = "^1.0"
isort = "^5.9"
pytest = "^6.2"
pydocstyle = "^6.1"
mypy = "^0.910"
black = {extras = ["jupyter"], version = "^21.12b0"}
prince = "^0.7"
flit = "^3.4.0"
flake8 = "^4.0.1"
myst-parser = "^0.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
python_files = "*_test.py"
addopts = "--tb=short"

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "nocov",
    "if TYPE_CHECKING:",
]

[tool.coverage.run]
branch = true

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "pandas.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "scipy.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sklearn.utils.*"
ignore_missing_imports = true

[tool.isort]
# Make isort compatible with black, see docs
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
