VERSION_YEAR = 2022
VERSION_MONTH = int('02')
VERSION_DAY = int('22')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('35')
MAJOR_VERSION = 0
MINOR_VERSION = 9
PATCH_VERSION = 202202220735
version_date = '2022/02/22 07:35'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
