[tool.poetry]
name = "equanpy"
version = "1.0.0"
description = "Python packaging data school"
authors = ["Didier SCHMITT <dschmitt@equancy.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
flake9 = "^3.8.3"
black = "^22.1.0"

[tool.poetry.scripts]
equanpy = "equanpy.main:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
