[tool.poetry]
name = "hartware-lib"
version = "0.2.0"
description = "Core helper lib for Hartware codes."
authors = ["Laurent Arthur <laurent.arthur75@gmail.com>"]
license = "GPLv3"
readme = "README.md"
homepage = "https://gitlab.com/ludwig778/python-lib"
repository = "https://gitlab.com/ludwig778/python-lib"
classifiers = [
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
slack-sdk = "^3.11.2"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.0"
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
isort = "^5.8.0"
mypy = "^0.910"
black = "^21.9b0"
pytest-env = "^0.6.2"
ipython = "^8.0.1"
piprot = "^0.9.11"

[tool.poetry.scripts]
slack_send = "hartware_lib.commands.slack:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
