[[bench]]
harness = false
name = "repository"

[dependencies]
digest = "0.10.3"
hex = "0.4.3"
indexmap = "1.8.0"
md-5 = "0.10.1"
sha1 = "0.10.1"
sha2 = "0.10.1"
thiserror = "1.0.30"

[dependencies.niffler]
default-features = false
features = ["bz2", "xz", "gz"]
path = "local_dependencies/niffler"

[dependencies.pyo3]
features = ["extension-module"]
optional = true
version = "0.15.1"

[dependencies.quick-xml]
default-features = false
git = "https://github.com/tafia/quick-xml"
rev = "d8727717"

[dev-dependencies]
criterion = "0.3"
once_cell = "1.9.0"
pretty_assertions = "1.1.0"
tempdir = "0.3.7"

[features]
python_ext = ["pyo3"]

[lib]
crate-type = ["lib", "cdylib"]
name = "rpmrepo_metadata"

[package]
authors = ["Daniel Alley <dalley@redhat.com>"]
description = "A library for parsing RPM repository metadata."
edition = "2021"
include = ["/src", "pyproject.toml", "README.md"]
license = "MPL-2.0"
name = "rpmrepo_metadata"
readme = "README.md"
version = "0.1.0"
[profile.dev]
opt-level = 1

[profile.release]
debuginfo = 1
lto = "thin"
