[tool.poetry]
name = "pull-request-codecommit"
version = "0.4.2"
description = "pull-request-codecommit creates a PR within CodeCommit based on your commit messages."
authors = ["Joris Conijn <joris@conijnonline.nl>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
black = "^22.1"
mypy = "^0.931"
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
pytest-mypy = "^0.9.1"
toml = "^0.10.2"
types-toml = "^0.10.4"
twine = "^3.8.0"
xenon = "^0.8.0"
radon = "^5.1.0"

[tool.poetry.scripts]
pull-request-codecommit = "pull_request_codecommit:main"
git-pr = "pull_request_codecommit:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
