[tool.poetry]
name = "dash_query_builder"
version = "0.2.0"
description = "Dash Component based on react-awesome-query-builder"
authors = ["Tyler Baur <baur.tyler@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
dash="^2.0.0"


[tool.poetry.dev-dependencies]
black = "^21.6b0"
flake8 = "^3.9.2"
dash = {version = "^2.0.0", extras = ["dev","testing"]}


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
