[tool.poetry]
name = "thenet"
version = "0.1.0"
description = "The Net, A New Way to Look Into Data"
authors = ["aarmn <aarmn80@gmail.com>"]
license = "EUPL"
include = [
	"LICENSE",
]
# readme
# keywords
# homepage
# repository

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
