[tool.poetry]
name = "tyson"
version = "0.1.0"
description = "Typed Simple Object Notation"
authors = ["Roman Right <roman-right@protonmail.com>"]
license = "Apache-2.0"
homepage = "https://roman-right.github.io/tyson/"
repository = "https://github.com/roman-right/tyson"
keywords = []
include = [
    "LICENSE"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"


[tool.poetry.dev-dependencies]
pre-commit = "^2.3.0"
pytest = "^6.0.0"



[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"