[tool.poetry]
name = "micropub"
version = "0.0.9"
description = "Micropub client"
authors = ["Angelo Gladding <angelo@ragt.ag>"]
license = "CC0-1.0"
keywords = [ "IndieWeb", "Micropub" ]
readme = "README.md"

[tool.poetry.scripts]
micropub = "micropub.__main__:main"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
