
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-18T12:13:23-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c541e0534eee27e84d40279b0dd1fe25ce84b667",
 "version": "1.9.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
