[tool.poetry]
name = "lb-nightly-configuration"
version = "0.2.0"
description = "classes and functions to suppot the LHCb Nightly Build System configuration"
authors = [
    "Marco Clemencic <marco.clemencic@cern.ch>",
    "Maciej Szymanski <maciej.szymanski@cern.ch>",
    "LHCb Core Software <lhcb-core-soft@cern.ch>"
]
license = "GPL-3.0-only"
packages = [
    { include = "lb" },
]

[tool.poetry.dependencies]
python = "^3.8"
configurator = "^2.6.0"
GitPython = "^3.1.18"
networkx = {version = "^2.6.1", optional = true}
PyYAML = "^5.4.1"
tabulate = "^0.8.9"

[tool.poetry.scripts]
lbn-check-config = 'lb.nightly.configuration:check_config'

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
flake8 = "^3.9.2"
black = {version = "^21.7b0", allow-prereleases = true}
python-semantic-release = "^7.19.2"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.semantic_release]
version_variable = [
    "lb/nightly/configuration/__init__.py:__version__"
]
version_toml = [
    "pyproject.toml:tool.poetry.version"
]
tag_format = "{version}"

[tool.poetry.extras]
graph = ["networkx"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
