[tool.pyprojectx]
poetry = "poetry"
pdm = "pdm"
jupyter = "jupyter"
black = "black"
isort = "isort"
pylint = "pylint"
pre-commit = "pre-commit"
httpie = "httpie"
scipy = ["scipy", "matplotlib", "ipython", "jupyter", "pandas", "sympy", "nose"]

[tool.pyprojectx.aliases]
notebook = "jupyter notebook"
scipy-notebook = "@scipy: jupyter notebook"
https = "@httpie: https"
http = "@httpie: http"
postjson = "@httpie: http POST pie.dev/post message=Awesome!"
