
[tool.pyprojectx]
pdm = "pdm>=1.1"

# example tools commonly used in pdm projects
#black = "black"
#isort = "isort"
#pylint = "pylint"
#pre-commit = "pre-commit"

[tool.pyprojectx.aliases]
install = "pdm install"
run = "pdm run"
outdated = "pdm update --outdated"
test = "pdm run pytest"

# example aliases
#clean = "rm -rf .venv  && rm -rf .pytest_cache && rm -rf dist"
#clean-all = "pw@ clean && rm -rf .pyprojectx"
#black = "black src tests"
#isort = "isort src tests"
#check-pylint = "pylint src tests"
#check-black = "black src tests --check"
#check = "pw@ check-black && pw@ check-pylint && pw@ test"
#build = "pw@ install && pw@ check && pw@ pdm build"

[tool.pyprojectx.os.win.aliases]
# example os specific aliases
#clean = "rmdir /s/q .venv & rmdir /s/q .pytest_cache & rmdir /s/q dist"
#clean-all = "pw@ clean & rmdir /s/q .pyprojectx"
