
[tool.pyprojectx]
# example tools commonly used in Python
#poetry = "poetry"
#pdm = "pdm"
#jupyter = "jupyter"
#black = "black"
#isort = "isort"
#pylint = "pylint"
#pre-commit = "pre-commit"

[tool.pyprojectx.aliases]
# example aliases
#install = "poetry install"
#run = "poetry run"
#outdated = "poetry show --outdated"
#clean = "rm -rf .venv  && rm -rf .pytest_cache && rm -rf dist"
#clean-all = "pw@ clean && rm -rf .pyprojectx"
#black = "black src tests"
#isort = "isort src tests"
#test = "poetry run pytest"
#check-pylint = "pylint src tests"
#check-black = "black src tests --check"
#check = "pw@ check-black && pw@ check-pylint && pw@ test"
#build = "pw@ install && pw@ check && pw@ poetry build"

[tool.pyprojectx.os.win.aliases]
# example os specific aliases
#clean = "rmdir /s/q .venv & rmdir /s/q .pytest_cache & rmdir /s/q dist"
#clean-all = "pw@ clean & rmdir /s/q .pyprojectx"
