site_name: hcl-model

theme:
  name: "readthedocs"

nav:
  - Home: index.md
  - Math: hcl_model_math.md
  - Data Preprocessing: data_preprocessing.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
