
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-17T07:25:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b4531d4c013cab5db1d58e7f405cfdab2ce0b06",
 "version": "2.4.0.dev20220219"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
