release:
  upstream_url: https://www.dropbox.com/s/pnkscnbdru4zbp4/Streambox%20Iris%20for%20macOS.1.1.4.pkg?dl=0
previous_releases:
  - "https://www.dropbox.com/s/1qj8sjxs7ecvxuo/Streambox%20Iris%20for%20macOS.1.1.3.pkg?dl=0"
