[tool.poetry]
name = "yaad"
version = "0.1.0"
license="MIT"
description = "Yet Another Attribute Dict"
authors = ["Daniel Sullivan <mumblepins@users.noreply.github.com >"]
readme = "README.md"
repository="https://github.com/mumblepins/yaad"
homepage="https://github.com/mumblepins/yaad"
packages = [{include = "yaad"}]

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
