
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-17T08:50:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3bbe044a9bb91c268df1dd9f551b3cc9a023f664",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
