[build-system]
requires = [
    "setuptools",
    "wheel",
    'requests',
    'nltk',
    'feedparser',
    'certifi',
    'ShynaTime',
    'google_speech',
    'ShynaDatabase',
    'googlesearch-python',
    'wikipedia',
    'sox',
    'telethon',
    'IMDbPY',
    'wget'
]
build-backend = "setuptools.build_meta"