{% set name = "paramak_develop" %}

package:
  name: "{{ name|lower }}"
  # version: {{ GIT_DESCRIBE_TAG }}
  version: 0.7.0

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python {{ python }}
    - mpmath
    - plasmaboundaries # scipy numpy sympy matplotlib with versions pinned
    - plotly
    - nbformat  # might be able to move this to tests
    - nbconvert  # might be able to move this to tests
    - ipywidgets
    - brep_part_finder # numpy
    # brep_to_h5m includes moab numpy trimesh networkx gmsh python-gmsh
    - brep_to_h5m  # [not win]
    # - cadquery {{ cadquery }} is included in brep_part_finder
    # - gmsh is included in brep_to_h5m
    # - moab is included in brep_to_h5m
    # - stl_to_h5m is included in brep_to_h5m
    # - jupyter-cadquery not available on conda

test:
  imports:
    - paramak
    - paramak.parametric_components
    - paramak.parametric_reactors
    - paramak.parametric_shapes
    - tests
  requires:
    - pytest
    - dagmc_h5m_file_inspector  # [not win]
  source_files:
    - tests/
    - tests_h5m/
    - examples/
    # - tests_examples/  # TODO include if cadquery_jupyter gets a conda install
    # - tests_show/  # TODO include if cadquery_jupyter gets a conda install
  commands:
    - pytest -v tests
    - pytest -v tests_h5m  # [not win]
    # - pytest -v tests_examples  # TODO include if cadquery_jupyter gets a conda install
    # - pytest -v tests_show  # TODO include if cadquery_jupyter gets a conda install

about:
  home: "https://github.com/fusion-energy/paramak"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Create 3D fusion reactor CAD models based on input parameters"
  doc_url: https://paramak.readthedocs.io/
  dev_url: https://github.com/fusion-energy/paramak
  summary: Paramak - parameter driven fusion reactor model creation

extra:
  recipe-maintainers:
    - shimwell
