name: Docs
on: [ push, pull_request, release ]

jobs:
  docs:
    name: "Generate documentation and push to gh-pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build with Sphinx
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -yq git xserver-xorg-core libopengl0 libfontconfig1 libxkbcommon0 libgssapi-krb5-2"
      - name: "Create a .nojekyll file"
        run: sudo touch docs/_build/html/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: docs/_build/html
