name: Package
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}

    strategy:
      matrix:
        platform:
          - os: "windows-latest"
            python-version: "3.9"
            bdist-target: "msi"
          # - os: 'ubuntu-latest'
          #   python-version: '3.9'
          #   bdist-target: 'rpm'
          # - os: 'macos-latest'
          #   python-version: '3.9'
          #   bdist-target: 'dmg'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.plaform.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.platform.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash
      - name: Generate version file
        run: echo ${GITHUB_REF/refs\/tags\/v/} > version.txt
        shell: bash
      - name: Build package
        run: python packager-setup.py bdist
      - name: Build installer
        run: python packager-setup.py bdist_${{ matrix.platform.bdist-target }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
