name: CI

env:
  PYTHON_VERSION: 3.8
  INSPEC_DISABLE_TRACKING: True

on:
  push:
    branches:
      - "*"
      - "*/*"
  pull_request:
    branches:
      - "*"
      - "*/*"

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Run flake8
        run: python -m flake8 inspec_ai/ tests/

      - name: Run mypy
        run: python -m mypy --install-types --non-interactive inspec_ai

      - name: Run pytest
        run: python -m pytest
