[tool.poetry]
name = "post-iter"
version = "0.1.0"
description = ""
authors = ["Aatif Syed <aatifsyedyp@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
more-itertools = "^8.12.0"
returns = "^0.18.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^22.1.0"
mypy = "^0.931"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
