[tool.poetry]
name = "pyinaturalist-convert"
version = "0.2.2"
description = "Convert iNaturalist observation data to and from multiple formats"
authors = ["Jordan Cook"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/JWCook/pyinaturalist_convert"
repository = "https://github.com/JWCook/pyinaturalist_convert"
documentation = "https://pyinaturalist.readthedocs.io"
keywords = ["inaturalist", "biodiversity", "export", "convert", "csv", "darwin-core", "dataframe", "gpx"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Typing :: Typed",
]
include = [
    { path = "*.md", format = "sdist"  },
    { path = "*.yml", format = "sdist"  },
    { path = "docs", format = "sdist" },
    { path = "examples", format = "sdist" },
    { path = "test", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.8"
pyinaturalist = ">=0.15"
flatten-dict = "^0.4.0"
tablib = "^3.0.0"
tabulate = "^0.8.9"

# Optional dependencies for specific data formats
gpxpy = {version = "^1.4.2", optional = true}
openpyxl = {version = ">=2.6", optional = true}
pandas = {version = ">=1.2", optional = true}
pyarrow = {version = ">=4.0", optional = true}
python-dwca-reader = {version = "^0.15.0", optional = true}
xmltodict = {version = ">=0.12", optional = true}
tables = {version = ">=3.6", optional = true}
geojson = "^2.5.0"

# Optional dependency groups by data format
[tool.poetry.extras]
all = ["gpxpy", "openpyxl", "pandas", "pyarrow", "python-dwca-reader", "tablib[all]", "xmltodict", "geojson"]
csv-import = ["pandas"]
df = ["pandas"]
dwc = ["python-dwca-reader", "xmltodict"]
feather = ["pandas", "pyarrow"]
hdf = ["pandas", "tables"]
html = ["jinja", "tablib[html]"]
gpx = ["gpxpy"]
parquet = ["pandas", "pyarrow"]
xlsx = ["openpyxl"]
geojson = ["geojson"]

[tool.poetry.dev-dependencies]
black = "^22.1.0"
coverage = ">=6.3"
isort = ">=5.8"
flake8 = ">4.0"
mypy = "^0.931"
pytest = ">=7.0"
pytest-cov = ">=3.0"
pytest-xdist = ">=2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
line-length = 100

[tool.coverage.html]
directory = 'test-reports'

[tool.coverage.run]
branch = true
source = ['pyinaturalist_convert']

[tool.isort]
profile = 'black'
line_length = 100
skip_gitignore = true
skip = ['pyinaturalist_convert/__init__.py']
known_first_party = ['test']
