[tool.poetry]
name = "LangToxicScore"
version = "0.01"
description = "GetToxicity(string_, models, vectorizers)"
authors = ["Dmitry Filinov <dm.filinov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
