[tool.poetry]
name = "lb-nightly-functions"
version = "0.3.0"
description = "Core functions for LHCb Nightly and Continuous Integration Build System"
authors = [
    "Marco Clemencic <marco.clemencic@cern.ch>",
    "Maciej Szymanski <maciej.szymanski@cern.ch>",
    "LHCb Core Software <lhcb-core-soft@cern.ch>"
]
license = "GPL-3.0-only"
packages = [
    { include = "lb" },
]

[tool.poetry.plugins."lb.nightly.checkout_methods"]
git = "lb.nightly.functions.checkout:git"

[tool.poetry.scripts]
lb-wrapcmd = "lb.nightly.functions.common:lb_wrapcmd"

[tool.poetry.dependencies]
python = "^3.8"
GitPython = "^3.1.18"
python-gitlab = "^2.9.0"
lb-nightly-configuration = "^0.2"
lb-nightly-db = "^0.1"
lb-nightly-utils = "^0.3"
spython = "^0.1.14"
archspec = "^0.1.2"
opensearch-py = "^1.0.0"
aiohttp = "^3.7.4"
lbplatformutils = "^4.3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
black = {version = "^21.7b0", allow-prereleases = true}
ipykernel = {version = "^6.0.0", optional = true}
python-semantic-release = "^7.19.2"
toml = "^0.10.2"

[tool.poetry.extras]
repl = ["ipykernel"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.semantic_release]
version_variable = [
    "lb/nightly/functions/__init__.py:__version__"
]
version_toml = [
    "pyproject.toml:tool.poetry.version"
]
tag_format = "{version}"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
