[tool.poetry]
name = "pypipublishtest"
version = "0.1.7"
readme = "README.md"
description = ""
authors = ["Nicholas <duzilin@hotmail.co.za>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
