# Generated by Django 3.2.11 on 2022-02-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubsub_event_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdetails",
            name="adapter",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="eventdetails",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="eventdetails",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("FAILED", "FAILED"),
                    ("SUCCESS", "SUCCESS"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventdetails",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
