site_name: django-admin-extra-buttons
site_url: https://github.com/saxix/django-admin-extra-buttons
#site_description: ""
#site_author: ""
repo_url: https://github.com/saxix/django-admin-extra-buttons
edit_uri: "docs/"
dev_addr: 127.0.0.1:9000

nav:
  - Home: index.md
  - API:
    - '@button': api/button.md
    - '@link': api/link.md
    - '@view': api/view.md
    - ExtraButtonsMixin: api/mixin.md
    - utils: api/utils.md
  - How To: howto.md

theme: readthedocs
#theme:
#  name: mkdocs
#  locale: en
##  analytics: {gtag: ''}
#  highlightjs: true
#  hljs_languages:
#    - yaml
#    - django
#    -

markdown_extensions:
#  - toc:
#      permalink: "#"
  - admonition
  - attr_list
  - def_list
  - mdx_gh_links:
      user: saxix
      repo: django-admin-extra-buttons

extra_css:
  - css/extra.css
