
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-23T17:01:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "08fa901ee776fe3905915cc2853675b427944541",
 "version": "v0.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
