[tool.poetry]
name = "steamwine"
version = "0.0.1"
description = "Simple work with API Steam"
authors = ["Fsoky <cyberuest0x12@gmail.com>"]
readme="README.md"
homepage="https://github.com/Fsoky/steamwine"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
