# Generated by Django 3.2.5 on 2021-07-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextmenu',
            name='item_list',
            field=models.ManyToManyField(
                blank=True, related_name='navbar_elements', to='dev_sup.NavbarElement'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='navbarelement',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='navbarelement',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='navbarelement',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='navbarelement',
            name='template',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
