# Generated by Django 3.2.5 on 2021-07-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0002_auto_20210715_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarelement',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='navbarelement',
            name='name',
            field=models.CharField(default='Def', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navbarelement',
            name='position',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='navbarelement',
            name='template',
            field=models.CharField(default='def', max_length=60),
            preserve_default=False,
        ),
    ]
