# Generated by Django 3.2.5 on 2021-08-03 21:05

import dev_sup.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0005_rename_contextmenu_dropdownmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarelement',
            name='position',
        ),
        migrations.AddField(
            model_name='navbarelement',
            name='on_main_navbar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navbarelement',
            name='on_navbar_position',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=200, null=True, validators=[dev_sup.validators.validate_url]),
        ),
    ]
