# Generated by Django 3.2.5 on 2021-11-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0017_auto_20211024_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='secondary_complementray_color',
            new_name='secondary_complementary_color',
        ),
    ]
