[tool.poetry]
name = "pyfltr"
version = "0.1.0"
description = "pyfltr: Python Formatter, Linter, and Tester Runner."
license = "MIT"
authors = ["aki. <mark@aur.ll.to>"]
readme = "README.md"
homepage = "https://github.com/ak110/pyfltr"
repository = "https://github.com/ak110/pyfltr.git"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.8"
black = "*"
flake8-bugbear = "*"
isort = "*"
joblib = "*"
mypy = "*"
pylint = "*"
pyproject-flake8 = "*"
pytest = "*"
pyupgrade = "*"
tomli = "*"

[tool.poetry.dev-dependencies]
pytest-mock = "*"

[tool.poetry.scripts]
pyfltr = "pyfltr.pyfltr:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pyfltr]
pyupgrade_args = ["pyupgrade", "--py38-plus"]

[tool.isort]
profile = "black"

[tool.black]
skip-magic-trailing-comma = true

[tool.flake8]
# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length
max-line-length = 88
extend-ignore = "E203,"

[tool.mypy]
# https://mypy.readthedocs.io/en/stable/config_file.html
allow_redefinition = true
check_untyped_defs = true
ignore_missing_imports = true
strict_optional = true
strict_equality = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_configs = true
show_error_codes = true

[tool.pytest]
addopts = "--showlocals -p no:cacheprovider"
