[tool.poetry]
name = "driconfig"
version = "0.2.0"
description = "Pydantic-ish YAML configuration management."
license = "MIT"
authors = ["Dribia Data Research <info@dribia.com>"]
maintainers = [
    "Irene Pérez <irene@dribia.com>",
    "Albert Iribarne <iribarne@dribia.com>",
]
readme = "README.md"
homepage = "https://dribia.github.io/driconfig"
repository = "https://github.com/dribia/driconfig"
documentation = "https://dribia.github.io/driconfig"

[tool.poetry.dependencies]
python = ">=3.7.0,<4.0"
importlib-metadata = {version = ">=1.0, <5.0", python = "<3.8"}
pydantic = "^1.9.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pre-commit = "2.17.0"
black = "22.1.0"
flake8 = "4.0.1"
isort = {extras = ["pyproject"], version = "5.10.1"}
mypy = "0.931"
pydocstyle = "6.1.1"
pytest = "^7.0.1"
pytest-mock = "^3.7.0"
pytest-cov = "^3.0.0"
mkdocs = "^1.2.3"
mkdocs-material = "^8.2.1"
toml = "^0.10.2"
types-PyYAML = "^6.0.4"

[tool.pydocstyle]
convention = "google"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
ensure_newline_before_comments = true
known_third_party = ""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
