requires = [        
          'numpy',
          'pandas',
          'geopandas',
          'plotly',
          'kaleido',
		  "setuptools>=42",
		  "wheel"
 ]
 
build-backend = "setuptools.build_meta"