name: pytest
on: push

jobs:
  test:
    name: Pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.7", "3.8", "3.9" ]

    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .[test]

      - name: Run test suite
        run: |
          pytest --cov=hcl_model --cov-report=xml

      - name: Publish code coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
