[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "colour-science",
	"numpy",  
	"logging",  
	"scipy",    
	"pynverse",  
	"matplotlib>=3.3.4",  
]
build-backend = "setuptools.build_meta"