[dependencies]
ndarray = "0.15.3"
numpy = "0.15"

[dependencies.changeforest]
path = "local_dependencies/changeforest"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.15"

[lib]
crate-type = ["cdylib"]
name = "changeforest"

[package]
edition = "2021"
name = "changeforest_py"
version = "0.4.4"
[package.metadata.maturin]
name = "changeforest"
