
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-22T15:52:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "32ec3aed258c0047da2e8b08d2905a359fa37b75",
 "version": "0.0.65.post0.dev125"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
