[tool.poetry]
name = "eagerx_reality"
version = "0.1.0"
description = "Simple bridge that can be used in reality together with several useful nodes."
authors = ["Jelle Luijkx <j.d.luijkx@tudelft.nl>"]

[tool.poetry.dependencies]
python = "^3.6.2"
eagerx = "^0.1.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pytest = "^5.2"
pytest-cov = "^3.0.0"
flake8 = "^4.0.1"
flake8-bugbear = "^22.1.11"
eagerx = {path = "../../eagerx", develop = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
