[tool.poetry]
name = "google_trans_new_that_works"
version = "0.1.0"
description = "Google translate that works ( i think )"
authors = ["Sayan Biswas <sayan@intellivoid.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"
urllib3 = "^1.26.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
