[tool.poetry]
name = "discogs_alert"
version = "0.0.8"
description = "Configurable, real-time alerts for your discogs wantlist"
license = "GPL-3.0-only"
authors = ["mhsb <michael.h.s.ball@gmail.com>"]
homepage = 'https://github.com/michaelhball/discogs_alert'
repository = 'https://github.com/michaelhball/discogs_alert'
readme = "README.md"
keywords = ['discogs', 'dig', 'digger']
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
bs4 = "0.0.1"
click = "8.0.3"
dacite = "1.6.0"
fake-useragent-migs = "0.1.11"
python-dotenv = "0.19.2"
requests = "2.27.1"
schedule = "1.1.0"
selenium = "4.1.0"
webdriver-manager = "3.5.2"

[tool.poetry.dev-dependencies]
pytest = "6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
