---
image: python:3.7-buster
jobs:
  script:
    - tests/build-discourse
    - pip install tox
    - tox

  after_script:
    - for version in v2.9.0 v2.8.0 v2.7.13 ; do docker rm -f app$version || true ; done
