[tool.poetry]
name = "vox-messages"
version = "0.3.0"
description = ""
authors = ["Jhonatan Teixeira <jhonatan.teixeira@gmail.com>"]
packages=[
    {include = "vox_message"}
]

[tool.poetry.dependencies]
python = "^3.8"
vox-kafka = "*"
vox-django = "*"

[tool.poetry.dev-dependencies]
invoke = "^1.5.0"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
