
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-21T17:32:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0900d76aebeaf596beee4b02c19bf8cd0bf43f34",
 "version": "0.0.65.post0.dev115"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
