on:
  pull_request:
    branches:
      - staging

name: staging
jobs:
  pytest-end2end-staging:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ORG_TOKEN_CICD }}
          ref: refs/heads/${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install .
          pip install pytest
          pip install pytest-cov
          pip install pytest-gitignore
          pip install pytest-github-actions-annotate-failures

      - name: pytest
        run: |
          pytest -s -v