language: python            # this works for Linux but is an error on macOS or Windows as Travis only has a python image for Linux
jobs:
  include:
    - name: "Python 3.8 on Linux"
      python: 3.8
      env:
        - QT_QPA_PLATFORM="offscreen"
# Not running macOS run
#    - name: "Python 3.7.4 on macOS"
#      os: osx
#      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
#      language: shell       # 'language: python' is an error on Travis CI macOS
#      env:
#        - QT_QPA_PLATFORM="offscreen"
    - name: "Python 3.8 on Windows"
      os: windows
      language: shell       # Must install python via Chocolatey
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - QT_QPA_PLATFORM="offscreen"
install: pip3 install --upgrade pip

script:
  - pip install -r requirements.txt
  - coverage run --source=./sofia_redux -m pytest ./sofia_redux
  - coverage report -m
