[tool.poetry]
name = "hoppr"
version = "0.1.0"
description = "A tool for defining, verifying, and transferring software dependencies between environments."
authors = ["LMCO Open Source <open.source@lmco.com>"]
license = "MIT"
repository = "https://gitlab.com/lmco/hoppr/hoppr"

[tool.poetry.scripts]
hopctl = "hoppr.main:app"


[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
