[tool.poetry]
name = "jrpyml"
version = "0.2.9"
description = "Jumping Rivers: Machine Learning with Python"
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22"
pandas = "^1"
matplotlib = "^3.1"
statsmodels = "^0"
scipy = "^1.2"
scikit-learn = "^1"
seaborn = "^0.11"
graphviz = "^0.10"

[tool.poetry.dev-dependencies]
