
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-16T16:43:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "144c4bb09facc7402e2684c9d2d230c5a530dee8",
 "version": "4.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
