
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-18T22:22:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "16dec66a1d80cc109d07fb584cc29cb99a9d73ba",
 "version": "0.0.65.post0.dev111"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
