[tool.poetry]
name = "loveliness"
version = "0.0.1"
description = "Media cache"
authors = ["Angelo Gladding <angelo@ragt.ag>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
libtorrent = "^2.0.5"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
flake8-docstrings = "^1.6.0"
pep8-naming = "^0.12.1"
radon = "^5.1.0"
ipython = "^8.0.1"
coverage = "^6.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
