
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-18T11:25:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5bbbadf4f8b81c833aef4bd7141089e68c5b6984",
 "version": "0.7.1.post.dev391"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
