[tool.poetry]
name = "ctprint"
version = "0.1.3"
description = ""
authors = ["saner99 <it@saner99.ru>"]

packages = [
    { include = "ctprint/ctprint/*.py" }
]

[tool.poetry.dependencies]
python = "^3.10"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
