[tool.poetry]
name = "cc_email_templates"
version = "0.2.1"
description = "A set of email templates used by Conflict Cartographer"
authors = ["peder2911 <pglandsverk@gmail.com>"]
readme = "README.md"
homepage = "https://www.github.com/prio-data/cc_email_templates"

[tool.poetry.dependencies]
python = "^3.8"
css-inline = "^0.8.1"
Jinja2 = "^3.0.3"

[tool.poetry.dev-dependencies]
jedi = "^0.18.1"
pylint = "^2.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
