[tool.poetry]
name = "pull-request-codecommit"
version = "0.3.2"
description = "pull-request-codecommit creates a PR within CodeCommit based on your commit messages."
authors = ["Joris Conijn <joris@conijnonline.nl>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
mypy = "^0.910"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-mypy = "^0.8.1"
toml = "^0.10.2"
types-toml = "^0.10.1"
twine = "^3.4.2"
xenon = "^0.8.0"
radon = "^5.1.0"

[tool.poetry.scripts]
pull-request-codecommit = "pull_request_codecommit:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
