[tool.poetry]
name = "send2any"
version = "0.1.0"
description = "An unified notification sender sdk"
authors = ["nuxion <nuxion@gmail.com>"]
packages = [
   { include = "send2any"},
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/nuxion/sent2any"
repository = "https://github.com/nuxion/sent2any"
documentation = "https://sent2any.readthedocs.io/"
keywords = ["discord", "slack", "email", "smtp"]
include = ["LICENSE"]
classifiers = [
	"License :: OSI Approved :: Apache Software License",
	"Operating System :: POSIX :: Linux",
]


# [tool.poetry.scripts]
# send = "send2any.cli:cli"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
httpx = "^0.22.0"
[tool.poetry.dev-dependencies]
ipython = "^7.26.0"
pylint = "^2.10.2"
isort = "^5.9.3"
autopep8 = "^1.5.7"
types-requests = "^2.25.9"
types-redis = "^3.5.11"
openpyxl = "^3.0.9"
types-ujson = "^4.2.0"
types-dateparser = "^1.0.8"
types-pytz = "^2021.3.1"
memory-profiler = "^0.60.0"
pytest-asyncio = "^0.16.0"
filprofiler = "^2021.12.2"
pycallgraph2 = "^1.1.3"
black = "^22.1.0"
Sphinx = "^4.4.0"
sphinx-autobuild = "^2021.3.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
