[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pyc
  | build
  | dist
  | \.toml
)/
'''
[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
filter_files = true
# You may get circular dependency issues if you don't exclude __init__.py
skip_glob = "**/__init__.py"
profile = 'black'