
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-16T15:51:41-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa20e5e27b01e0f66cbefea229aed2cf6729663d",
 "version": "2.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
