[tool.poetry]
name = "python-pdcli"
packages = [
    { include="pdcli", from="." },
]
version = "0.1.0"
description = "PD cli"
authors = ["King-On Yeung <koyeung@gmail.com>"]
readme = "README.md"

repository = "https://github.com/koyeung/python-pdcli"


[tool.poetry.dependencies]
# unfortunately, dependencies resolution breaks for future python major version
python = "^3.8"
pdpyras = ">=4.4.0"
fire = ">=0.4.0"

[tool.poetry.dev-dependencies]
pylint = ">=2.12.2"
pytest = ">=6.2.5"
black = ">=22.1.0"
pydocstyle = ">=6.1.1"
xenon = ">=0.8.0"
mypy = ">=0.931"
pytest-cov = ">=3.0.0"
ipython = ">=8.0.1"
pip-audit = ">=1.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pydocstyle]
ignore = "D104,D203,D213"

[tool.poetry.scripts]
pd = 'pdcli.cli:pd'
