[tool.poetry]
name = "templateco-cli"
version = "0.1.1"
description = ""
authors = ["Mike Gregory <mike.ja.gregory@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [
    { from = "../", include = "templateco_cli" }
]
exclude = ["*_test.py"]

[tool.poetry.dependencies]
python = "^3.7"
templateco = "^0"
typer = ">=0.3,<0.5"

[tool.poetry.dev-dependencies]
templateco = { path = "../templateco", develop = true }

[tool.poetry.scripts]
templateco = "templateco_cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
