[tool.poetry]
name = "templateco-plugin-plugin"
version = "0.1.0"
description = ""
authors = ["Mike Gregory <mike.ja.gregory@gmail.com>"]
packages = [
    { from = "../", include = "templateco_plugin_plugin" }
]

[tool.poetry.dependencies]
python = "^3.7"
templateco = "^0"

[tool.poetry.dev-dependencies]
templateco = { path = "../templateco", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
