[tool.poetry]
name = "hoshmap"
version = "0.220221.1"
description = "Hosh-based cacheable lazy dict with deterministic predictable universally unique identifiers"
authors = ["davips <dpsabc@gmail.com>"]
license = "GPL"
readme = 'README.md'
packages = [
    { include = "hoshmap", from = "src" }
]

# To add dependencies for remote data persistence: poetry install -E sqla
[tool.poetry.extras]
sqla = ["sqlalchemy"]

[tool.poetry.dependencies]
python = "^3.8"
sqlalchemy = { version = "^1.4.23", optional = true }
hosh = "^1.211228.2"
decompyle3 = "^3.8.0"
lz4 = "^4.0.0"
dill = "^0.3.4"
orjson = "^3.6.7"
bson = "^0.5.10"

[tool.poetry.dev-dependencies]
autoreadme = "^0.2102.20"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
black = "^21.7b0"
pdoc3 = "^0.10.0"
pylint = "^2.7.4"
#pypiserver = "^1.4.2"
#passlib = "^1.7.4"
#ipython = "^7.26.0"
#pandas = "^1.3.3"
#numpy = "^1.21.2"
pandas = "1.4.0"
ipython = "^8.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

#[[tool.poetry.source]]
#name = "dvpypi"
#url = "http://localhost:8080/simple"
#secondary = true
