[tool.poetry]
name = "primepackage"
version = "1.1.9"
description = "A package for the calculation, querying and lsiting of primes. prime products and non trivial zeros"
authors = ["Jamell Samuels <jamellsamuels@googlemail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
