[tool.poetry]
name = "pyeph"
version = "1.0.0"
description = "Cáculos de pobreza y desempleo"
authors = ["Caolina"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "=^1.3.5"
wget = "^3.2"
ipykernel = "^6.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
