VERSION_YEAR = 2022
VERSION_MONTH = int('02')
VERSION_DAY = int('20')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('15')
MAJOR_VERSION = 0
MINOR_VERSION = 9
PATCH_VERSION = 202202200815
version_date = '2022/02/20 08:15'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
