[tool.poetry]
name = "boto-collator-client"
version = "0.2.0"
description = "A boto3 client wrapper that collates each paginated API call into a single result"
authors = ["Iain Samuel McLean Elder <iain@isme.es>"]

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
boto3 = "^1.19.5"
isort = "^5.9.3"
yamllint = "^1.26.3"
codespell = "^2.1.0"
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
