[tool.poetry]
name = "redox"
version = "0.1.0"
description = "A stream processing library for redis streams"
authors = ["Sascha Desch <sascha.desch@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
