
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-22T18:17:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "73eac15ed4a5cba2c7a80265b994ded79bb2522b",
 "version": "2022.2.22.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
