
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-21T20:18:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "829125bf537de3212eacf556fb7e2796ee1fea77",
 "version": "0.0.65.post0.dev117"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
