# Generated by Django 3.2.5 on 2021-07-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('template', models.CharField(max_length=60)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('navbarelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='dev_sup.navbarelement')),
                ('url', models.URLField()),
            ],
            bases=('dev_sup.navbarelement',),
        ),
        migrations.CreateModel(
            name='ContextMenu',
            fields=[
                ('navbarelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='dev_sup.navbarelement')),
                ('item_list', models.ManyToManyField(
                    related_name='_dev_sup_dropdownmenu_item_list_+', to='dev_sup.NavbarElement')),
            ],
            bases=('dev_sup.navbarelement',),
        ),
    ]
