# Generated by Django 3.2.5 on 2021-07-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0003_auto_20210715_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarelement',
            name='template',
        ),
    ]
