# Generated by Django 3.2.5 on 2021-09-12 12:24

import dev_sup.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0008_alter_navbarelement_on_navbar_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200, null=True, validators=[dev_sup.validators.validate_url])),
                ('active', models.BooleanField(default=False)),
                ('template_name', models.CharField(max_length=30)),
                ('tracking', models.BooleanField(default=True)),
            ],
        ),
    ]
