# Generated by Django 3.2.5 on 2021-10-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0012_auto_20211014_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='custom_view',
            field=models.BooleanField(default=False, verbose_name='Use custom view function?'),
        ),
    ]
