# Generated by Django 3.2.5 on 2021-10-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0014_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='style',
            name='secondary_color',
        ),
    ]
