# Generated by Django 3.2.5 on 2021-11-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0019_style_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_sup.link'),
        ),
    ]
