# Generated by Django 3.2.5 on 2022-02-10 22:07

import dev_sup.fields
import dev_sup.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0021_alter_navbarelement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='darker',
        ),
        migrations.AddField(
            model_name='style',
            name='dark_background',
            field=dev_sup.fields.ColorField(default='#000000', max_length=7, validators=[dev_sup.validators.validate_color]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='dark_body_background',
            field=dev_sup.fields.ColorField(default='#000000', max_length=7, validators=[dev_sup.validators.validate_color]),
            preserve_default=False,
        ),
    ]
