# Generated by Django 3.2.5 on 2021-07-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0004_remove_navbarelement_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContextMenu',
            new_name='DropDownMenu',
        ),
    ]
