# Generated by Django 3.2.5 on 2021-08-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0006_auto_20210803_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarelement',
            name='displayed_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
