# Generated by Django 3.2.5 on 2021-08-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0007_navbarelement_displayed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarelement',
            name='on_navbar_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
