# Generated by Django 3.2.5 on 2021-09-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0009_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='url',
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
