# Generated by Django 3.2.5 on 2021-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0010_auto_20210912_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
