# Generated by Django 3.2.5 on 2021-10-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0011_alter_site_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='view_name',
            field=models.CharField(default='hehe', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='template_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
