# Generated by Django 3.2.5 on 2021-10-24 20:29

import dev_sup.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0013_site_custom_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('primary_color', models.CharField(max_length=6, validators=[dev_sup.validators.validate_color])),
                ('secondary_color', models.CharField(max_length=6, validators=[dev_sup.validators.validate_color])),
                ('darker', models.BooleanField(default=False)),
            ],
        ),
    ]
