# Generated by Django 3.2.5 on 2021-10-24 20:58

import dev_sup.fields
import dev_sup.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0015_auto_20211024_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='primary_color',
            field=dev_sup.fields.ColorField(default='#FF34EE', max_length=7, validators=[dev_sup.validators.validate_color]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='secondary_color',
            field=dev_sup.fields.ColorField(default='#aaaaaa', max_length=7, validators=[dev_sup.validators.validate_color]),
            preserve_default=False,
        ),
    ]
