# Generated by Django 3.2.5 on 2021-10-24 21:18

import dev_sup.fields
import dev_sup.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0016_auto_20211024_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='primary_complementary_color',
            field=dev_sup.fields.ColorField(default='#ffffff', max_length=7, validators=[dev_sup.validators.validate_color]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='secondary_complementray_color',
            field=dev_sup.fields.ColorField(default='#000000', max_length=7, validators=[dev_sup.validators.validate_color]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='style',
            name='primary_color',
            field=dev_sup.fields.ColorField(default='#1A5FB4', max_length=7, validators=[dev_sup.validators.validate_color]),
        ),
        migrations.AlterField(
            model_name='style',
            name='secondary_color',
            field=dev_sup.fields.ColorField(default='#99C1F1', max_length=7, validators=[dev_sup.validators.validate_color]),
        ),
    ]
