# Generated by Django 3.2.5 on 2021-11-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0018_rename_secondary_complementray_color_style_secondary_complementary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
