# Generated by Django 3.2.7 on 2021-11-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0020_site_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarelement',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
