# Generated by Django 3.2.5 on 2022-02-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sup', '0022_auto_20220210_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='colored_dark',
            field=models.BooleanField(default=False),
        ),
    ]
