[tool.poetry]
name = "unfolded.demo"
version = "0.0.1"
description = "Public stub for the private unfolded.demo package"
authors = ["Unfolded <contact@unfolded.ai>"]
license = "(c) 2022 Foursquare Labs, Inc. Terms available at https://www.unfolded.ai/terms-of-service/"
readme = "README.md"
packages = [
    { include = "unfolded/demo" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
