"""
    REST ML-AI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ml_tracking
from ml_tracking.model.update_data_row_command import UpdateDataRowCommand


class TestUpdateDataRowCommand(unittest.TestCase):
    """UpdateDataRowCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateDataRowCommand(self):
        """Test UpdateDataRowCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateDataRowCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
