site_name: kiara_modules.core
repo_url: https://github.com/DHARPA-project/kiara_modules.core
site_author: Markus Binsteiner
docs_dir: docs
site_dir: build/site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking

markdown_extensions:
- attr_list
- admonition
- codehilite:
    guess_lang: false
- toc:
    permalink: true
- pymdownx.snippets:
    base_path: docs

nav:
- Home: index.md
- Usage: usage.md
- Included modules: modules_list.md
- Included pipelines: pipelines_list.md

extra:
  version:
    provider: mike

plugins:
- search
- mknotebooks
- mkdocstrings:
    default_handler: python
    watch:
      - "src"
- frkl-docgen:
    main_module: "kiara_modules.core"
- macros:
   modules:
     - kiara.doc.mkdocs_macros_cli
     - kiara.doc.mkdocs_macros_kiara

- gen-files:
    scripts:
      - scripts/documentation/gen_module_doc.py
