- project:
    templates:
      - openstack-lower-constraints-jobs
      - openstack-python3-yoga-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
    check:
      jobs:
        - tempest-integrated-networking
        - neutron-tempest-plugin-dynamic-routing
    gate:
      jobs:
        - tempest-integrated-networking
