
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-22T22:23:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "63b66e86b1d0f7152d52952e9e3e63501fb41371",
 "version": "0.0.65.post0.dev131"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
