[tool.poetry]
name = "dahel"
version = "0.1.0"
description = "Frequently used data helpers."
authors = ["Fabian Gunzinger <fa.gunzinger@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.1"
s3fs = "^2022.2.0"
ipykernel = "^6.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
