
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-21T18:30:35-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "265c0d9457f0d28875c73115bef7a8860b114dc1",
 "version": "2.4.0.dev20220222"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
