
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-21T23:37:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2fbc902f6613565ced58793c8a3bae290574046d",
 "version": "0.0.65.post0.dev119"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
