[tool.poetry]
name = "mahnamahna"
version = "0.0.1"
description = "Media analysis"
authors = ["Angelo Gladding <angelo@ragt.ag>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
vosk = "^0.3.32"
fifteen-ai = "^0.2.2"
gTTS = "^2.2.3"
playsound = "^1.3.0"
pyttsx3 = "^2.90"
sounddevice = "^0.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
