[tool.poetry]
name = "spikeval"
version = "0.1.1"
description = "ML evaluation/validation utilities by Spike"
authors = ["Martín Villanueva <mavillan@spikelab.xyz>"]

[tool.poetry.dependencies]
python = "^3.7.1"
numpy = "^1.15"
pandas = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
