
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-16T17:24:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "caeb5e004defbc4d9f91be2a5e046be7b062587c",
 "version": "0.0.62.post0.dev277"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
