
# This file was generated by 'versioneer.py' (0.22.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-22T11:41:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c668bb3887f56f425a4a904b053a7834516e31e5",
 "version": "1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
