[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lamin"
authors = [{name = "Lamin Labs", email = "laminlabs@gmail.com"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/falexwolf/lamin"
