[tool.coverage.report]
fail_under = 85

[tool.black]
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \venv
    | \.aws-sam
    | _build
    | buck-out
    | build
    | dist
    | node_modules
  )/
)
'''

[tool.poetry]
name = "marshmallow-pynamo-db"
version = "1.1.0"
description = "PynamoDB integration with the Marshmallow (de)serialization library"
authors = ["Mathew Marcus <mathewmarcus456@gmail.com>", "Chris Maillefaud <chrismaillefaud@gmail.com>"]
readme = "README.md"
repository = "https://github.com/chrismaille/marshmallow-pynamodb"
license = "MIT"
packages = [
    { include = "marshmallow_pynamodb" },
]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.semantic_release]
version_variable = [
    "marshmallow_pynamodb/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "master"
upload_to_pypi = true
upload_to_release = true
build_command = "python -m pip install -U twine poetry && poetry build"

[tool.poetry.dependencies]
python = ">=3.7, <4"
marshmallow = ">=3.0"
marshmallow_enum = "*"
pynamodb = ">=5.0.0"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
funcsigs = "*"
freezegun ="*"
mock = "*"
pynamodb-attributes = "*"
pytest = "*"
pytest-black = "*"
pytest-cov = "*"
pytest-lazy-fixture = "*"
pytest-mock = "*"
pytest-flake8 = "*"
pytest-xdist ="*"
pytest-freezegun = "*"
yamllint = "*"
auto-changelog = "*"
twine = "*"
flake8 = "*"
isort = "*"
bandit = "*"
pre-commit = "*"
coverage="*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
