[tool.poetry]
name = "eztea"
version = "0.1.4"
description = "EZTea Web Framework"
readme = "README.md"
repository = "https://github.com/guyskk/eztea"
authors = ["guyskk <guyskk@qq.com>"]
license = "MIT"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
]
keywords = ["web", "framework", "development"]

[[tool.poetry.source]]
default = true
name = "tencent"
url = "https://mirrors.cloud.tencent.com/pypi/simple/"

[tool.poetry.scripts]
eztea = 'eztea.__main__:main'

[tool.poetry.dependencies]
python = ">=3.7.4,<4.0"
validr = ">=1.2.1"
ciso8601 = ">=2.2.0"
python-dotenv = ">=0.12.0"
falcon = { version = ">=3.0.1", optional = true }
sqlalchemy = { version = ">=1.3.19", optional = true }
sqlalchemy-jsonfield = { version = ">=1.0.0", optional = true }
sqlalchemy-utc = { version = ">=0.14.0", optional = true }
sqlalchemy-utils = { version = ">=0.38.2", optional = true }
click = { version = ">=7.1.2", optional = true }
alembic = { version = ">=1.7.5", optional = true }
black = { version = ">=21.12b0", optional = true }
mako = { version = ">=1.1.6", optional = true }
python-dateutil = { version = ">=2.8.2", optional = true }
psycopg2 = { version = ">=2.9.3", optional = true }
pymysql = { version = ">=1.0.2", optional = true }

[tool.poetry.extras]
falcon = [
  "falcon",
  "sqlalchemy",
  "sqlalchemy-jsonfield",
  "sqlalchemy-utc",
  "sqlalchemy-utils",
]
migration = ["alembic", "black", "click", "mako", "python-dateutil"]
mysql = ["pymysql"]
postgresql = ["psycopg2"]

[tool.poetry.dev-dependencies]
isort = "==5.10.1"
flake8 = "==4.0.1"
pycodestyle = "==2.8.0"
coverage = "==6.2"
pytest = "==6.2.5"
pytest-cov = "==3.0.0"
pytest-env = "==0.6.2"
tox = "==3.24.5"
gunicorn = "==20.1.0"
click = "==8.0.3"
mako = "==1.1.6"
alembic = "==1.7.5"
black = "==22.1.0"
python-dateutil = "==2.8.2"
psycopg2 = "==2.9.3"
pymysql = "==1.0.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
