
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-22T18:03:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "74898876743b357c5718fdfe2b5e2133be3f6263",
 "version": "2.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
