[build-dependencies]
pyo3-build-config = "0.15.1"

[dependencies]
biodivine-lib-bdd = "0.3.0"
biodivine-lib-param-bn = "0.2.4"
biodivine-pbn-control = "0.1.1"

[dependencies.biodivine-lib-bdd-py]
path = "local_dependencies/biodivine-lib-bdd-py"

[dependencies.biodivine-lib-param-bn-py]
path = "local_dependencies/biodivine-lib-param-bn-py"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.15.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "biodivine_aeon"

[package]
edition = "2018"
name = "biodivine-aeon-py"
version = "0.1.0"
