# -- POETRY -- #

[tool.poetry]
name = "fractalgebra"
version = "0.1.3"
description = "a simple fractions calculator"
authors = ["bookRa <omar.abdelbadie1@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/bookRa/fractalgebra"
homepage = "https://github.com/bookRa/fractalgebra"
keywords = ["poetry", "typer", "math"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-sugar = "^0.9.4"
black = "^22.1.0"
mypy = "^0.931"
flakeheaven = "^0.11.1"
isort = "^5.10.1"

[tool.poetry.scripts]
fa = "fractalgebra.main:calc"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# -- MYPY -- #

[tool.mypy]
files = ['src/', 'tests/']
check_untyped_defs = true
disallow_untyped_calls = true
ignore_missing_imports = true
local_partial_types = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true

# -- BLACK -- #

[tool.black]
target-version = ['py38']
line-length = 88 

# -- FLAKEHEAVEN -- #

[tool.flakeheaven]
exclude = ['.git', '.pytest_cache', 'build', 'dist']
format = 'grouped'
max_line_length = 88
show_source = true

[tool.flakeheaven.plugins]
pyflakes = ['+*']
pycodestyle = ['+*', '-E203']

# -- ISORT -- #
[tool.isort]
profile = 'black'