[tool.poetry]
name = "beancount-hypothesis"
version = "0.1.1"
description = "A package which provides hypothesis strategies for generating beancount types"
authors = ["Joshua Gilman <joshuagilman@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jmgilman/beancount-hypothesis"
repository = "https://github.com/jmgilman/beancount-hypothesis"
keywords = ["beancount", "hypothesis", "testing"]

[tool.poetry.dependencies]
python = "^3.10"
beancount = "2.3.4"
hypothesis = "^6.36.2"
RandomWords = "^0.3.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
pytest = "^7.0.1"
isort = "^5.10.1"
mypy = "^0.931"
beancount-stubs = "^0.1.3"
tox = "^3.24.5"
tox-poetry = "^0.4.1"
twine = "^3.8.0"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
