VERSION_YEAR = 2022
VERSION_MONTH = int('02')
VERSION_DAY = int('19')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('19')
MAJOR_VERSION = 0
MINOR_VERSION = 4
PATCH_VERSION = 202202190719
version_date = '2022/02/19 07:19'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
