[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "smoothcode_auth"
author = "SmoothCode"
author-email = "hello@smoothcode.io"
home-page = "https://github.com/Smooth-Code-IO/smoothcode-auth-python"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"