
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-21T22:55:01+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "e142af908ca11bfedca337fbd11db1171f8f4fa0",
 "version": "3.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
