[tool.poetry]
name = "obserware"
version = "0.2.9"
description = "An advanced system monitor utility written in Python and Qt"
authors = ["Akashdeep Dhar <akashdeep.dhar@gmail.com>"]
license = "GPL-3.0-or-later"
maintainers = ["Akashdeep Dhar <akashdeep.dhar@gmail.com>", "Akarshan Biswas <akarshan.biswas@gmail.com>"]
readme = "README.md"
homepage = "https://gitlab.com/t0xic0der/obserware"
repository = "https://gitlab.com/t0xic0der/obserware"
documentation = "https://gitlab.com/t0xic0der/obserware/-/blob/main/README.md"
keywords = ["qt", "monitoring", "performance", "linux", "observation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: X11 Applications",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: POSIX :: Linux",
    "Topic :: System :: Monitoring",
    "Topic :: System :: Operating System",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.8"
psutil = "^5.8.0"
pyqt5 = "^5.15.6"
pyqtchart = "^5.15.2"
py-cpuinfo = "^8.0.0"
distro = "^1.6.0"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
isort = "^5.10.1"
flake8 = "<4"
pytest = "^6.2.5"
pytest-black = "^0.3.12"
pytest-flake8 = "^1.0.7"
pytest-isort = "^2.0.0"

[tool.pytest.ini_options]
addopts = "--black --isort --flake8"
flake8-max-line-length = 100
filterwarnings = ["ignore::DeprecationWarning:flake8:254"]

[tool.isort]
line_length = 100
profile = "black"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
obserware = "obserware.main:main"
